baseURL = "https://quanganhtranngo.github.io/"
languageCode = "en-us"
title = "Quang-Anh Ngo Tran"
theme = 'barks'

[params.colors]
    theme_color = "#fcfbf9"
    background_color = "#333333"
    text_color = "#fcfbf9"
    link_color = "#60c17d"
    
[params.head]
    author = "Quang-Anh Ngo Tran"
    custom_css = "style.css"
    description = "Quang-Anh Ngo Tran's Homepage"
    keywords = ["alex", "Quang-Anh", "Ngo", "tran", "psychology", "iu", "indiana", "university"]

[params.navigation]
    show_navigation = true

[params.footer]
    show_footer = true

[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:quatran@iu.edu"
        weight = 1
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square"
        url = "https://scholar.google.com/citations?user=DZCxUJAAAAAJ"
        weight = 2
    [params.social.LinkedIn]
        name = "LinkedIn"
        class = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/quang-anh-tran-345696173/"
        weight = 3
    [params.social.Twitter]
        name = "Twitter"
        class = "fab fa-twitter"
        url = "https://twitter.com/QuangAnhTranNgo"
        weight = 4
    [params.social.MyInstitution]
        name = "My Institution"
        class = "fas fa-university"
        url = "https://socialroles.lab.indiana.edu/people/index.html"
        weight = 5 

[menu]
    [[menu.main]]
        identifier = 'About'
        name = 'About'
        url = '/about/'
        weight = -130
    [[menu.main]]
        identifier = 'Research'
        name = 'Research'
        url = '/research/'
        weight = -120
    [[menu.main]]
        identifier = 'Teaching'
        name = 'Teaching'
        url = '/teaching/'
        weight = -110
    [[menu.main]]
        identifier = 'Awards & Honors'
        name = 'Awards & Honors'
        url = '/awards/'
        weight = -100
    [[menu.main]]
        identifier = 'CV'
        name = 'CV'
        url = '/CV/'
        weight = -90
    [[menu.main]]
        identifier = 'Blogs'
        name = 'Blogs'
        url = '/blogs/'
        weight = -80
